// Self-signed localhost certificate (valid 100 years) for the https tunnel test only.
export const TEST_TLS_CERT = `-----BEGIN CERTIFICATE-----
MIIBnDCCAUGgAwIBAgIUAu8zofOCEzz51WSKH0IevIKJI1cwCgYIKoZIzj0EAwIw
FDESMBAGA1UEAwwJbG9jYWxob3N0MCAXDTI2MTAwMjIyMTc1NloYDzIxMjYwOTA4
MjIxNzU2WjAUMRIwEAYDVQQDDAlsb2NhbGhvc3QwWTATBgcqhkjOPQIBBggqhkjO
PQMBBwNCAARxtUSbv5ofsE+ycFlQqN7CXBhx9TtBBUddpiEhIyYYNfD1ZqVrobFS
7+kzka4Q4mNbQtSRWKhvIiGCbNML0Xxno28wbTAdBgNVHQ4EFgQUSGbzn0EqlQeg
D5p6mupYSlLgm+gwHwYDVR0jBBgwFoAUSGbzn0EqlQegD5p6mupYSlLgm+gwDwYD
VR0TAQH/BAUwAwEB/zAaBgNVHREEEzARgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZI
zj0EAwIDSQAwRgIhAPfA0WLOIOySpIaPy4nCr/oDeeURDbe+u8WwJWkJTHGOAiEA
9VGPdOVQaFe1HN47YuAnShsXoubaByDzJOeO3xKbdlg=
-----END CERTIFICATE-----`;
export const TEST_TLS_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgErTke2eFTzL9xhJ9
iExcz32e+oLTGeRW+vkEJRNQZu2hRANCAARxtUSbv5ofsE+ycFlQqN7CXBhx9TtB
BUddpiEhIyYYNfD1ZqVrobFS7+kzka4Q4mNbQtSRWKhvIiGCbNML0Xxn
-----END PRIVATE KEY-----`;
