import { IsArray, IsString } from 'class-validator';
import type { IAgentChatToolDefinition, TAgentChatMessage } from '../agent-chat.types.js';

/**
 * `messages`/`tools` are validated only as arrays, not deep-validated field-by-field: they're
 * `@falang/agent`'s own discriminated-union/JSON-Schema shapes, generated by that package and never
 * hand-typed by a user — a malformed request here only breaks the requesting user's own agent run
 * (caught by `AgentSession`'s try/catch), it never reaches another user's data or the compiled build.
 *
 * No `credentialId`/`model` — the model resolves from the app-wide `AgentSettingsService` config
 * instead, see ADR 0031 (private).
 */
export class AgentChatRequestDto {
  @IsString()
  system!: string;

  @IsArray()
  messages!: TAgentChatMessage[];

  @IsArray()
  tools!: IAgentChatToolDefinition[];
}
