/**
 * Generated by Falang
 *
 * Scheme template: function
 **/
// Falang:icon-start:function                0146555021
// Falang:icon-start:file_header             0898694433
#include <iostream>
#include "helloWorld.h"

using namespace std;
// Falang:icon-end:file_header               0898694433
// Falang:icon-start:function_header         1856160423
void helloWorld(int iteration)
// Falang:icon-end:function_header           1856160423
{
  int _continueValue = 0;
  int _breakValue = 0;
  // Falang:icon-start:skewer                1399404606
  // Falang:icon-start:action                0764600491
  cout<<"Hello, World! "<<iteration;
  // Falang:icon-end:action                  0764600491
  // Falang:icon-start:action                0990805498
  cout<<endl;
  // Falang:icon-end:action                  0990805498
  // Falang:icon-end:skewer                  1399404606
  // Falang:icon-start:function_footer       0923781143
  // Falang:icon-end:function_footer         0923781143
}
// Falang:icon-end:function                  0146555021