/**
 * Generated by Falang
 *
 * Scheme template: function
 **/
// Falang:icon-start:function                0329567369
// Falang:icon-start:file_header             2058259576
#include "helloWorld.h"
// Falang:icon-end:file_header               2058259576
// Falang:icon-start:function_header         1421120821
int main()
// Falang:icon-end:function_header           1421120821
{
  int _continueValue = 0;
  int _breakValue = 0;
  // Falang:icon-start:skewer                1447636357
  // Falang:icon-start:foreach               1166969686
  for(int i = 1; i < 10; i++)
  {
    // Falang:icon-start:skewer              1377093060
    // Falang:icon-start:action              0239725399
    helloWorld(i);
    // Falang:icon-end:action                0239725399
    // Falang:icon-end:skewer                1377093060
  }
  // Falang:icon-end:foreach                 1166969686
  // Falang:icon-end:skewer                  1447636357
  // Falang:icon-start:function_footer       1537272470
  return 0;
  // Falang:icon-end:function_footer         1537272470
}
// Falang:icon-end:function                  0329567369