import { contextBridge, ipcRenderer } from 'electron';
import type {
  ICreateProjectParams,
  IDocumentLock,
  IGitVersioningOptions,
  IProjectChangeEvent,
  IProjectManifest,
  IProjectTree,
} from '@falang/desktop-project-fs';
import type { IProjectDocument, IProjectTreeFolder } from '@falang/dto';
import type { ILogicExportConfiguration, ILogicExportConfigurationItem } from '@falang/logic-dto';
import type { IAgentSettings, IChatResult, IChatToolDefinition, TChatMessage } from '@falang/desktop-llm-client';
import type { IChatSession, IChatSessionSummary, IChatTurn } from '@falang/agent';
import type { IExportWorkerProgress, TExportWorkerResult } from '../shared/export-worker-protocol.js';
import type { ICommitInfo, IProjectSnapshot, TCommitKind } from '@falang/versioning';
import { IPC } from '../shared/ipc-channels.js';
import type { IRecentProject } from '../shared/recent-project.js';
import type { IProjectOpenResult } from '../shared/project-open-result.js';
import type { INewProjectLocationSuggestion } from '../shared/new-project-location.js';

const subscribe =
  (channel: string) =>
  (listener: (...args: unknown[]) => void): (() => void) => {
    const wrapped = (_event: unknown, ...args: unknown[]) => listener(...args);
    ipcRenderer.on(channel, wrapped);
    return () => ipcRenderer.off(channel, wrapped);
  };

const falangApi = {
  dialog: {
    openProjectFolder: (): Promise<string | null> => ipcRenderer.invoke(IPC.dialogOpenProjectFolder),
    // `defaultPath` seeds the native picker with the dialog's current directory field (see
    // `new-project-dialog-store.ts`'s `selectDirectory`) — omit it for the picker's own default.
    newProjectFolder: (defaultPath?: string): Promise<string | null> =>
      ipcRenderer.invoke(IPC.dialogNewProjectFolder, defaultPath),
  },
  project: {
    create: (dir: string, params: ICreateProjectParams): Promise<IProjectManifest> =>
      ipcRenderer.invoke(IPC.projectCreate, dir, params),
    open: (dir: string): Promise<IProjectOpenResult> => ipcRenderer.invoke(IPC.projectOpen, dir),
    listTree: (dir: string): Promise<IProjectTree> => ipcRenderer.invoke(IPC.projectListTree, dir),
    suggestNewLocation: (): Promise<INewProjectLocationSuggestion> => ipcRenderer.invoke(IPC.projectSuggestNewLocation),
    onChanged: subscribe(IPC.projectChanged) as (listener: (event: IProjectChangeEvent) => void) => () => void,
  },
  locks: {
    read: (dir: string): Promise<IDocumentLock[]> => ipcRenderer.invoke(IPC.locksRead, dir),
  },
  document: {
    read: (dir: string, documentId: string): Promise<IProjectDocument> =>
      ipcRenderer.invoke(IPC.documentRead, dir, documentId),
    write: (dir: string, document: IProjectDocument): Promise<void> =>
      ipcRenderer.invoke(IPC.documentWrite, dir, document),
    create: (dir: string, params: { document: IProjectDocument; folderId: string | null }): Promise<void> =>
      ipcRenderer.invoke(IPC.documentCreate, dir, params),
    delete: (dir: string, documentId: string): Promise<void> => ipcRenderer.invoke(IPC.documentDelete, dir, documentId),
    rename: (dir: string, documentId: string, name: string): Promise<void> =>
      ipcRenderer.invoke(IPC.documentRename, dir, documentId, name),
    move: (dir: string, documentId: string, folderId: string | null): Promise<void> =>
      ipcRenderer.invoke(IPC.documentMove, dir, documentId, folderId),
  },
  folder: {
    create: (dir: string, params: { name: string; parentId: string | null }): Promise<IProjectTreeFolder> =>
      ipcRenderer.invoke(IPC.folderCreate, dir, params),
    rename: (dir: string, folderId: string, name: string): Promise<void> =>
      ipcRenderer.invoke(IPC.folderRename, dir, folderId, name),
    move: (dir: string, folderId: string, parentId: string | null): Promise<void> =>
      ipcRenderer.invoke(IPC.folderMove, dir, folderId, parentId),
    delete: (dir: string, folderId: string): Promise<void> => ipcRenderer.invoke(IPC.folderDelete, dir, folderId),
  },
  recentProjects: {
    list: (): Promise<IRecentProject[]> => ipcRenderer.invoke(IPC.recentProjectsList),
    add: (projectPath: string, name: string): Promise<void> =>
      ipcRenderer.invoke(IPC.recentProjectsAdd, projectPath, name),
  },
  logicExport: {
    readConfig: (dir: string): Promise<ILogicExportConfiguration | null> =>
      ipcRenderer.invoke(IPC.logicExportReadConfig, dir),
    writeConfig: (dir: string, config: ILogicExportConfiguration): Promise<void> =>
      ipcRenderer.invoke(IPC.logicExportWriteConfig, dir, config),
    // Runs in a disposable child process (`@falang/desktop-worker-process`), not inline in `main` —
    // see `main/ipc-handlers.ts`'s own doc comment. `requestId` (generated by the caller) lets
    // `cancel` target this specific run and lets `onProgress` events be matched to it.
    run: (
      requestId: string,
      dir: string,
      params: { documents: IProjectDocument[]; exports: ILogicExportConfigurationItem[] },
    ): Promise<Extract<TExportWorkerResult, { kind: 'logic' }>> =>
      ipcRenderer.invoke(IPC.logicExportRun, requestId, dir, params),
    cancel: (requestId: string): Promise<void> => ipcRenderer.invoke(IPC.logicExportCancel, requestId),
    onProgress: subscribe(IPC.logicExportProgress) as (
      listener: (requestId: string, progress: IExportWorkerProgress) => void,
    ) => () => void,
  },
  codeExport: {
    // Same worker-process posture as `logicExport.run` above.
    run: (
      requestId: string,
      dir: string,
      params: { documents: IProjectDocument[] },
    ): Promise<Extract<TExportWorkerResult, { kind: 'code' }>> =>
      ipcRenderer.invoke(IPC.codeExportRun, requestId, dir, params),
    cancel: (requestId: string): Promise<void> => ipcRenderer.invoke(IPC.codeExportCancel, requestId),
    onProgress: subscribe(IPC.codeExportProgress) as (
      listener: (requestId: string, progress: IExportWorkerProgress) => void,
    ) => () => void,
  },
  settings: {
    getLanguage: (): Promise<string | null> => ipcRenderer.invoke(IPC.settingsGetLanguage),
    setLanguage: (language: string): Promise<void> => ipcRenderer.invoke(IPC.settingsSetLanguage, language),
    getAgentSettings: (): Promise<IAgentSettings | null> => ipcRenderer.invoke(IPC.settingsGetAgent),
    setAgentSettings: (settings: IAgentSettings): Promise<void> => ipcRenderer.invoke(IPC.settingsSetAgent, settings),
    getVersioningSettings: (): Promise<IGitVersioningOptions> => ipcRenderer.invoke(IPC.settingsGetVersioning),
    setVersioningSettings: (settings: IGitVersioningOptions): Promise<void> =>
      ipcRenderer.invoke(IPC.settingsSetVersioning, settings),
  },
  agent: {
    chat: (
      requestId: string,
      params: { system: string; messages: readonly TChatMessage[]; tools: readonly IChatToolDefinition[] },
    ): Promise<IChatResult> => ipcRenderer.invoke(IPC.agentChat, requestId, params),
    cancelChat: (requestId: string): Promise<void> => ipcRenderer.invoke(IPC.agentChatCancel, requestId),
  },
  // `IAgentSessionStore` over IPC, one method per `@falang/agent` interface method — see
  // ADR 0033 (private) and `renderer/src/agent/electron-agent-session-store.ts`,
  // which wraps this 1:1.
  agentSessions: {
    list: (dir: string): Promise<IChatSessionSummary[]> => ipcRenderer.invoke(IPC.agentSessionsList, dir),
    create: (dir: string, title?: string): Promise<IChatSession> =>
      ipcRenderer.invoke(IPC.agentSessionsCreate, dir, title),
    get: (dir: string, id: string): Promise<IChatSession | null> => ipcRenderer.invoke(IPC.agentSessionsGet, dir, id),
    rename: (dir: string, id: string, title: string): Promise<void> =>
      ipcRenderer.invoke(IPC.agentSessionsRename, dir, id, title),
    delete: (dir: string, id: string): Promise<void> => ipcRenderer.invoke(IPC.agentSessionsDelete, dir, id),
    appendTurn: (dir: string, sessionId: string, turn: IChatTurn): Promise<void> =>
      ipcRenderer.invoke(IPC.agentSessionsAppendTurn, dir, sessionId, turn),
  },
  // `IVersionStore` over IPC, one method per `@falang/versioning` interface method — see
  // ADR 0025 (private) (package E2) and `renderer/src/versioning/
  // electron-version-store.ts`, which wraps this 1:1.
  versioning: {
    listCommits: (dir: string): Promise<ICommitInfo[]> => ipcRenderer.invoke(IPC.versioningListCommits, dir),
    getSnapshot: (dir: string, commitId: string): Promise<IProjectSnapshot> =>
      ipcRenderer.invoke(IPC.versioningGetSnapshot, dir, commitId),
    getWorkingCopy: (dir: string): Promise<IProjectSnapshot> => ipcRenderer.invoke(IPC.versioningGetWorkingCopy, dir),
    hasExtraChanges: (dir: string): Promise<boolean> => ipcRenderer.invoke(IPC.versioningHasExtraChanges, dir),
    commit: (dir: string, params: { kind: TCommitKind; message: string }): Promise<ICommitInfo | null> =>
      ipcRenderer.invoke(IPC.versioningCommit, dir, params),
    nameCommit: (dir: string, commitId: string, message: string): Promise<ICommitInfo> =>
      ipcRenderer.invoke(IPC.versioningNameCommit, dir, commitId, message),
    restore: (dir: string, commitId: string): Promise<ICommitInfo> =>
      ipcRenderer.invoke(IPC.versioningRestore, dir, commitId),
  },
  print: {
    // Native save dialog + `webContents.printToPDF` in `main` (ADR 0048 (private)).
    toPdf: (params: { suggestedFileName: string }): Promise<{ canceled: true } | { path: string }> =>
      ipcRenderer.invoke(IPC.printToPdf, params),
  },
  menu: {
    onNewProject: subscribe(IPC.menuNewProject),
    onOpenProject: subscribe(IPC.menuOpenProject) as (listener: (recentPath?: string) => void) => () => void,
    onSaveDocument: subscribe(IPC.menuSaveDocument),
    onOpenExportConfig: subscribe(IPC.menuOpenExportConfig),
    onExportCode: subscribe(IPC.menuExportCode),
    onExportCodeDocuments: subscribe(IPC.menuExportCodeDocuments),
    onOpenSettings: subscribe(IPC.menuOpenSettings),
    onOpenVersioningSettings: subscribe(IPC.menuOpenVersioningSettings),
    onOpenLanguageSettings: subscribe(IPC.menuOpenLanguageSettings),
    onToggleVersionHistory: subscribe(IPC.menuToggleVersionHistory),
    onToggleAgent: subscribe(IPC.menuToggleAgent),
    onExportPdf: subscribe(IPC.menuExportPdf),
  },
  app: {
    // `main`'s graceful-close flow (see `main/index.ts`) — the window's `close` event is intercepted
    // once, this fires, and `flushBeforeCloseComplete` must be called (even with nothing pending) for
    // the window to actually close.
    onFlushBeforeClose: subscribe(IPC.appFlushBeforeClose),
    flushBeforeCloseComplete: (): void => ipcRenderer.send(IPC.appFlushBeforeCloseComplete),
  },
};

export type FalangApi = typeof falangApi;

contextBridge.exposeInMainWorld('falang', falangApi);
