/**
 * Generates `plugins/falang/skills/falang-arduino/references/driver-format.md` from the driver bundle's zod schema
 * (`DRIVER_BUNDLE_JSON_SCHEMA`, ADR 0054 (private)), so the skill's format reference cannot drift from what
 * `validate_driver`/`set_driver` accept. Run: `npm run generate:driver-format` (`--check` fails when the file is stale).
 */
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
// The workspace packages are CommonJS TypeScript — a default import is the only interop tsx's ESM loader offers.
import dto from '@falang/desktop-arduino-dto';

const {
  DRIVER_BUNDLE_FILE_SUFFIX,
  DRIVER_BUNDLE_JSON_SCHEMA,
  DRIVER_BUNDLE_MAX_FILE_BYTES,
  DRIVER_BUNDLE_MAX_TOTAL_BYTES,
} = dto;

interface ISchema {
  type?: string | string[];
  properties?: Record<string, ISchema>;
  required?: string[];
  items?: ISchema;
  enum?: unknown[];
  const?: unknown;
  pattern?: string;
  minItems?: number;
  minLength?: number;
  additionalProperties?: ISchema | boolean;
}

const describeType = (schema: ISchema): string => {
  if ('const' in schema) return `\`${JSON.stringify(schema.const)}\``;
  if (schema.enum) return schema.enum.map((value) => `\`${JSON.stringify(value)}\``).join(String.raw` \| `);
  if (schema.type === 'array') return `array of ${schema.items ? describeType(schema.items) : 'any'}`;
  if (schema.type === 'object' && schema.properties) return 'object';
  if (schema.type === 'object') {
    const value = schema.additionalProperties;
    return `map of string → ${typeof value === 'object' ? describeType(value) : 'any'}`;
  }
  return String(schema.type ?? 'any');
};

const constraints = (schema: ISchema): string => {
  const parts: string[] = [];
  if (schema.pattern) parts.push(`pattern \`${schema.pattern}\``);
  if (schema.minItems) parts.push(`at least ${schema.minItems} item(s)`);
  const inner = schema.items;
  if (inner?.pattern) parts.push(`each item matches \`${inner.pattern}\``);
  return parts.join('; ').replaceAll('|', String.raw`\|`);
};

const lines: string[] = [];
const walk = (title: string, schema: ISchema): void => {
  if (!schema.properties) return;
  lines.push(`### ${title}`, '', '| Field | Type | Required | Constraints |', '| --- | --- | --- | --- |');
  const nested: [string, ISchema][] = [];
  const required = new Set(schema.required);
  for (const [name, child] of Object.entries(schema.properties)) {
    lines.push(
      `| \`${name}\` | ${describeType(child)} | ${required.has(name) ? 'yes' : 'no'} | ${constraints(child)} |`,
    );
    if (child.type === 'object' && child.properties) nested.push([`${title}.${name}`, child]);
    if (child.type === 'array' && child.items?.properties) nested.push([`${title}.${name}[]`, child.items]);
  }
  lines.push('');
  for (const [nestedTitle, nestedSchema] of nested) walk(nestedTitle, nestedSchema);
};

const build = (): string => {
  lines.length = 0;
  lines.push(
    '<!-- GENERATED by plugins/falang/scripts/generate-driver-format.mts from the driver bundle zod schema — do not edit; run `npm run generate:driver-format`. -->',
    '',
    '# Driver bundle format',
    '',
    `A driver is one JSON document (\`*${DRIVER_BUNDLE_FILE_SUFFIX}\`, the shape \`validate_driver\`/\`set_driver\` take as \`bundle\`): ` +
      '`{ "formatVersion": 1, "config": <driver.config.json>, "files": { "<file name>": "<text>" } }`. ' +
      `Each file is at most ${DRIVER_BUNDLE_MAX_FILE_BYTES / 1024} KiB, the whole bundle at most ${DRIVER_BUNDLE_MAX_TOTAL_BYTES / 1024} KiB. ` +
      'On disk a driver is the folder `<id>/` holding `driver.config.json` and every file of `files`.',
    '',
    '## Fields',
    '',
  );
  walk('bundle', DRIVER_BUNDLE_JSON_SCHEMA as ISchema);
  lines.push(
    '## Rules the schema alone does not show',
    '',
    '- `files` must contain exactly the names in `config.sourceFiles` ∪ `config.includes` — no more, no fewer; file names are flat (no `/`).',
    '- A `${name}` in a `codeTemplate` or `device.setupTemplate` must be a declared field of that action/device. Values are substituted verbatim into C++; a `string` field is a TypeScript string expression.',
    '- An action has at most one `new-variable` field, and `resultType` (`int` / `float` / `bool` / `string`) is set exactly when it has one. A `select` field needs `options`, whose `value`s are integer literals. `device.fields` cannot be `new-variable`.',
    '- Every C function the templates call must be declared in `config.declarations` (`declare function name(arg: number): number;`) with a unique prefix: names are checked against built-ins and every other driver.',
    '- `notes` (driver, action) is plain English for the LLM and the node-kinds catalog — always fill it in.',
    '',
    '## Full JSON Schema',
    '',
    '```json',
    JSON.stringify(DRIVER_BUNDLE_JSON_SCHEMA, null, 2),
    '```',
    '',
  );
  return lines.join('\n');
};

const main = async (): Promise<void> => {
  const target = path.resolve(import.meta.dirname, '../skills/falang-arduino/references/driver-format.md');
  const next = build();
  if (process.argv.includes('--check')) {
    const current = await fs.readFile(target, 'utf8').catch(() => '');
    if (current !== next) {
      // oxlint-disable-next-line no-console -- CLI script
      console.error(`${target} is stale — run "npm run generate:driver-format"`);
      process.exitCode = 1;
    }
    return;
  }
  await fs.writeFile(target, next);
};

await main();
